apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260520-224623-p8d2g5ajvcy8-service
spec:
  selector:
    app: enterprise-system-20260520-224623-p8d2g5ajvcy8
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
